library(ROracle)
library(googledrive)
library(googlesheets4)
library(lubridate)
library(tidyverse)
library(jsonlite)
library(devtools)

# Add a dependency
use_package('fromJSON')
use_package('ROracle')
use_package('googlesheets4')
use_package('tidyverse')
use_package('jsonlite')
use_package('lubridate')
use_package('googledrive')
use_package('devtools')
